;<KHeader>
;+=========================================================================
;I  Project Name: EApiDK Embedded Application Development Kit
;+=========================================================================
;I  $HeadURL: https://sourceforge.net/p/eapidk/code/HEAD/tree/trunk/include/masm/EApi.inc $
;+=========================================================================
;I  SPDX-License-Identifier: BSD-3-Clause
;I  Copyright (C) 2019 Kontron Europe GmbH
;I  Author: John Kearney, John.Kearney@kontron.com
;I
;I Description: Auto Created for EApi.inc
;I
;+-------------------------------------------------------------------------
;I
;I  File Name            : EApi.inc
;I  File Location        : include\masm
;I
;+=========================================================================
;</KHeader>
IFNDEF __EApi_INC__
__EApi_INC__ TEXTEQU <>

        include <EApiMacro.inc>
        include <EApiConv.inc>

ENDIF  __EApi_INC__
