;<KHeader>
;+=========================================================================
;I  Project Name: EApiDK Embedded Application Development Kit
;+=========================================================================
;I  $HeadURL: https://sourceforge.net/p/eapidk/code/HEAD/tree/trunk/include/masm/EeeP.inc $
;+=========================================================================
;I  SPDX-License-Identifier: BSD-3-Clause
;I  Copyright (C) 2019 Kontron Europe GmbH
;I  Author: John Kearney, John.Kearney@kontron.com
;I
;I Description: Auto Created for EApi.inc
;I
;+-------------------------------------------------------------------------
;I
;I  File Name            : EeeP.inc
;I  File Location        : include\masm
;I
;+=========================================================================
;</KHeader>
IFNDEF __EEEP_INC__
__EEEP_INC__ TEXTEQU <>

        include <EeePConv.inc>

ENDIF  __EEEP_INC__
