/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (C) 2019 Kontron AG */

/* Generated by the KEAPI Generator, 2017.11.07 15:06:12 +0300
 * Do not edit manually.
 */

#include "keapi_inc.h"
#include "keapiNative.h"

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetLibVersion(PKEAPI_VERSION_DATA pVersion)
{
	if (pVersion == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetLibVersion(pVersion);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBoardInfo(PKEAPI_BOARD_INFO pBoardInfo)
{
	if (pBoardInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBoardInfo(pBoardInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBootCounter(int32_t *pBootCount)
{
	if (pBootCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBootCounter(pBootCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSystemUpTime(int32_t *pSystemUpTime)
{
	if (pSystemUpTime == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SystemUpTime(pSystemUpTime);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetIntruderStatus(int32_t *pIntruderStatus)
{
	if (pIntruderStatus == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetIntruderStatus(pIntruderStatus);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiResetIntruderStatus()
{
	return KEApiL_ResetIntruderStatus();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetPBITResult(uint32_t *pResult, uint32_t *pCumulativeResult)
{
	if (pResult == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (pCumulativeResult == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetPBITResult(pResult, pCumulativeResult);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiClearPBITResult()
{
	return KEApiL_ClearPBITResult();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetCpuFreq(int32_t coreNr, int8_t freqType, int32_t *pFrequency)
{
	if (pFrequency == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetCpuFreq(coreNr, freqType, pFrequency);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetCpuInfo(PKEAPI_CPU_INFO pCpuInfo)
{
	if (pCpuInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetCpuInfo(pCpuInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetCpuPerformance(int32_t coreNr, int8_t *pPerformancePercentage)
{
	if (pPerformancePercentage == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetCpuPerformance(coreNr, pPerformancePercentage);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetMemoryInfo(PKEAPI_MEMORY_INFO pMemoryInfo)
{
	if (pMemoryInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetMemoryInfo(pMemoryInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetDiskDriveCount(int32_t *pDiskDriveCount)
{
	if (pDiskDriveCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetDiskDriveCount(pDiskDriveCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetDiskDriveList(PKEAPI_DISK_DRIVE pDiskDrives, int32_t diskDriveCount)
{
	if (diskDriveCount < 0 || diskDriveCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pDiskDrives == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetDiskDriveList(pDiskDrives, diskDriveCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetDiskDriveSMARTAttrCount(int32_t diskNr, int32_t *pAttrCount)
{
	if (pAttrCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetDiskDriveSMARTAttrCount(diskNr, pAttrCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetDiskDriveSMARTAttrs(int32_t diskNr, PKEAPI_SMART_ATTR pAttrs, int32_t attrCount)
{
	if (attrCount < 0 || attrCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pAttrs == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetDiskDriveSMARTAttrs(diskNr, pAttrs, attrCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetMountPointCount(int32_t *pCount)
{
	if (pCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetMountPointCount(pCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetMountPointList(PKEAPI_MOUNT_POINT pMountPointList, int32_t mountPointCount)
{
	if (mountPointCount < 0 || mountPointCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pMountPointList == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetMountPointList(pMountPointList, mountPointCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBatteryCount(int32_t *pBatteryCount)
{
	if (pBatteryCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBatteryCount(pBatteryCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBatteryInfo(int32_t slotNr, PKEAPI_BATTERY_INFO pBatteryInfo)
{
	if (pBatteryInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBatteryInfo(slotNr, pBatteryInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBatteryState(int32_t slotNr, PKEAPI_BATTERY_STATE pBatteryState)
{
	if (pBatteryState == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBatteryState(slotNr, pBatteryState);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiPerformanceStateCaps(uint32_t *pStatesMask)
{
	if (pStatesMask == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_PerformanceStateCaps(pStatesMask);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetPerformanceStateDescription(uint32_t state, char *pDescription)
{
	if (KEAPI_MAX_STR < 0 || KEAPI_MAX_STR > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	if (pDescription == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetPerformanceStateDescription(state, pDescription);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetPerformanceState(uint32_t *pState)
{
	if (pState == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetPerformanceState(pState);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSetPerformanceState(uint32_t state)
{
	return KEApiL_SetPerformanceState(state);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetTempSensorCount(int32_t *pTempSensorCount)
{
	if (pTempSensorCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetTempSensorCount(pTempSensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetTempSensorValue(int32_t sensorNr, PKEAPI_SENSOR_VALUE pSensorValue)
{
	if (pSensorValue == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetTempSensorValue(sensorNr, pSensorValue);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetTempSensorValueList(PKEAPI_SENSOR_VALUE pSensorValues, int32_t sensorCount)
{
	if (sensorCount < 0 || sensorCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pSensorValues == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetTempSensorValueList(pSensorValues, sensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetTempSensorInfo(int32_t sensorNr, PKEAPI_SENSOR_INFO pSensorInfo)
{
	if (pSensorInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetTempSensorInfo(sensorNr, pSensorInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetVoltageSensorCount(int32_t *pVoltageSensorCount)
{
	if (pVoltageSensorCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetVoltageSensorCount(pVoltageSensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetVoltageSensorValue(int32_t sensorNr, PKEAPI_SENSOR_VALUE pSensorValue)
{
	if (pSensorValue == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetVoltageSensorValue(sensorNr, pSensorValue);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetVoltageSensorValueList(PKEAPI_SENSOR_VALUE pSensorValues, int32_t sensorCount)
{
	if (sensorCount < 0 || sensorCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pSensorValues == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetVoltageSensorValueList(pSensorValues, sensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetVoltageSensorInfo(int32_t sensorNr, PKEAPI_SENSOR_INFO pSensorInfo)
{
	if (pSensorInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetVoltageSensorInfo(sensorNr, pSensorInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetFanSensorCount(int32_t *pFanSensorCount)
{
	if (pFanSensorCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetFanSensorCount(pFanSensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetFanSensorValue(int32_t sensorNr, PKEAPI_SENSOR_VALUE pSensorValue)
{
	if (pSensorValue == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetFanSensorValue(sensorNr, pSensorValue);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetFanSensorValueList(PKEAPI_SENSOR_VALUE pSensorValues, int32_t sensorCount)
{
	if (sensorCount < 0 || sensorCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pSensorValues == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetFanSensorValueList(pSensorValues, sensorCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetFanSensorInfo(int32_t sensorNr, PKEAPI_SENSOR_INFO pSensorInfo)
{
	if (pSensorInfo == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetFanSensorInfo(sensorNr, pSensorInfo);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetDisplayCount(int32_t *pDisplayCount)
{
	if (pDisplayCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetDisplayCount(pDisplayCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetBacklightValue(int32_t displayNr, int32_t *pValue)
{
	if (pValue == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetBacklightValue(displayNr, pValue);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSetBacklightValue(int32_t displayNr, int32_t value)
{
	return KEApiL_SetBacklightValue(displayNr, value);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetNetworkDeviceCount(int32_t *pNetworkDeviceCount)
{
	if (pNetworkDeviceCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetNetworkDeviceCount(pNetworkDeviceCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetNetworkDeviceList(PKEAPI_NETWORK_DEVICE pNetworkDevices, int32_t networkDeviceCount)
{
	if (networkDeviceCount < 0 || networkDeviceCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pNetworkDevices == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetNetworkDeviceList(pNetworkDevices, networkDeviceCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetPciDeviceCount(int32_t *pPciDeviceCount)
{
	if (pPciDeviceCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetPciDeviceCount(pPciDeviceCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetPciDeviceList(PKEAPI_PCI_DEVICE pPciDevices, int32_t pciDeviceCount)
{
	if (pciDeviceCount < 0 || pciDeviceCount > MAX_KEAPI_COUNTER)
		return KEAPI_RET_PARAM_ERROR;
	if (pPciDevices == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetPciDeviceList(pPciDevices, pciDeviceCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetStorageCount(int32_t *pStorageCount)
{
	if (pStorageCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetStorageCount(pStorageCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetStorageSize(int32_t storageNr, int32_t *pStorageSize)
{
	if (pStorageSize == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetStorageSize(storageNr, pStorageSize);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiStorageRead(int32_t storageNr, int32_t offset, uint8_t *pData, int32_t dataLength)
{
	if (dataLength < 0 || dataLength > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	if (pData == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_StorageRead(storageNr, offset, pData, dataLength);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiStorageWrite(int32_t storageNr, int32_t offset, uint8_t *pData, int32_t dataLength)
{
	if (dataLength < 0 || dataLength > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	if (pData == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_StorageWrite(storageNr, offset, pData, dataLength);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetI2cBusCount(int32_t *pI2cBusCount)
{
	if (pI2cBusCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetI2cBusCount(pI2cBusCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiI2cXfer(int32_t i2cNr, uint8_t i2cAddress, uint8_t *pWriteData, int32_t writeLength,
					 uint8_t *pReadData, int32_t *pReadLength)
{
	if (pReadLength == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (writeLength < 0 || writeLength > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	if (*pReadLength < 0 || *pReadLength > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	return KEApiL_I2cXfer(i2cNr, i2cAddress, pWriteData, writeLength, pReadData, pReadLength);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiI2cProbe(int32_t i2cNr, uint8_t i2cAddress, uint8_t memoryAddress,
					  uint8_t memoryAddressUsed)
{
	return KEApiL_I2cProbe(i2cNr, i2cAddress, memoryAddress, memoryAddressUsed);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetSpiBusCount(int32_t *pSpiBusCount)
{
	if (pSpiBusCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetSpiBusCount(pSpiBusCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSpiXfer(int32_t spiNr, uint16_t deviceId, uint32_t command, uint8_t commandSize,
					 int32_t numTransfers, uint8_t *pWriteData, uint8_t *pReadData)
{
	if (numTransfers < 0 || numTransfers > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	if (numTransfers < 0 || numTransfers > MAX_KEAPI_BINARY)
		return KEAPI_RET_PARAM_ERROR;
	return KEApiL_SpiXfer(spiNr, deviceId, command, commandSize, numTransfers, pWriteData, pReadData);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetSmbusCount(int32_t *pSmbusCount)
{
	if (pSmbusCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetSmbusCount(pSmbusCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusQuickCommand(int32_t smbusNr, uint8_t smbusAddress, uint8_t operation)
{
	return KEApiL_SmbusQuickCommand(smbusNr, smbusAddress, operation);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusSendByte(int32_t smbusNr, uint8_t smbusAddress, uint8_t byte)
{
	return KEApiL_SmbusSendByte(smbusNr, smbusAddress, byte);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusReceiveByte(int32_t smbusNr, uint8_t smbusAddress, uint8_t *pByte)
{
	if (pByte == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SmbusReceiveByte(smbusNr, smbusAddress, pByte);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusWriteByte(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint8_t byte)
{
	return KEApiL_SmbusWriteByte(smbusNr, smbusAddress, command, byte);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusReadByte(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint8_t *pByte)
{
	if (pByte == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SmbusReadByte(smbusNr, smbusAddress, command, pByte);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusWriteWord(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint16_t word)
{
	return KEApiL_SmbusWriteWord(smbusNr, smbusAddress, command, word);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusReadWord(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint16_t *pWord)
{
	if (pWord == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SmbusReadWord(smbusNr, smbusAddress, command, pWord);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusWriteBlock(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint8_t *pData,
						 int8_t dataLength)
{
	if (dataLength < 0)
		return KEAPI_RET_PARAM_ERROR;
	if (pData == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SmbusWriteBlock(smbusNr, smbusAddress, command, pData, dataLength);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSmbusReadBlock(int32_t smbusNr, uint8_t smbusAddress, uint8_t command, uint8_t *pData,
						int8_t *pDataLength)
{
	if (pDataLength == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (*pDataLength < 0)
		return KEAPI_RET_PARAM_ERROR;
	if (pData == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_SmbusReadBlock(smbusNr, smbusAddress, command, pData, pDataLength);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetGpioPortCount(int32_t *pCount)
{
	if (pCount == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetGpioPortCount(pCount);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetGpioPortDirectionCaps(int32_t portNr, uint32_t *pIns, uint32_t *pOuts)
{
	if (pIns == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (pOuts == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetGpioPortDirectionCaps(portNr, pIns, pOuts);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetGpioPortDirections(int32_t portNr, uint32_t *pDirections)
{
	if (pDirections == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetGpioPortDirections(portNr, pDirections);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSetGpioPortDirections(int32_t portNr, uint32_t directions)
{
	return KEApiL_SetGpioPortDirections(portNr, directions);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiGetGpioPortLevels(int32_t portNr, uint32_t *pLevels)
{
	if (pLevels == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_GetGpioPortLevels(portNr, pLevels);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiSetGpioPortLevels(int32_t portNr, uint32_t levels)
{
	return KEApiL_SetGpioPortLevels(portNr, levels);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogGetCaps(int32_t *pMaxTimeout, int32_t *pMinTimeout, int32_t *pStagesNr)
{
	if (pMaxTimeout == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (pMinTimeout == NULL)
		return KEAPI_RET_PARAM_NULL;
	if (pStagesNr == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_WatchdogGetCaps(pMaxTimeout, pMinTimeout, pStagesNr);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogSetup(int32_t stage, int32_t timeout, int32_t mode)
{
	return KEApiL_WatchdogSetup(stage, timeout, mode);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogEnable()
{
	return KEApiL_WatchdogEnable();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogDisable()
{
	return KEApiL_WatchdogDisable();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogTrigger()
{
	return KEApiL_WatchdogTrigger();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogGetExpired(int32_t *pWTE)
{
	if (pWTE == NULL)
		return KEAPI_RET_PARAM_NULL;
	return KEApiL_WatchdogGetExpired(pWTE);
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogClearExpired()
{
	return KEApiL_WatchdogClearExpired();
}

KEAPI_CALLTYPE KEAPI_RETVAL KEApiWatchdogWaitUntilExpired()
{
	return KEApiL_WatchdogWaitUntilExpired();
}
